from setuptools import setup, find_packages

setup(
    name="reasoning-probing",
    packages=find_packages(),
    version="0.0.1",
    author="George Ma",
    install_requires=[
        "httpx>=0.22",
        "tiktoken",
        "numpy",
        "pytest",
        "orjson",
        "dacite",
        "torch",
        "torchvision",
        "einops",
        "jaxtyping",
        "datasets",
        "transformers",
        "tqdm",
        "wandb",
        "sae_lens",
        "transformer_lens",
        "sentence_transformers",
        "info-nce-pytorch",
        "pdbpp",
        "colorama",
        "bitsandbytes",
        "json-repair",
        "backoff",
        "openai",
    ],
    url="",
    description="",
    python_requires='>=3.9',
)
